[project]
name = "formal"
version = "0.7.0"
description = "Z3 solver and RL integration"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
    "z3-solver>=4.14.1.0",
]
